import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/sidebar/Sidebar';
import MainHeaderBar from '@/components/header/MainHeaderBar';

const archivo = Archivo({
  variable: '--font-archivo-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${archivo.variable} antialiased`}>
      <body>{children}</body>
    </html>
  );
}
