// import type { Metadata } from 'next';
// import { Archivo } from 'next/font/google';
// import '../globals.css';
// import Sidebar from '@/components/sidebar/Sidebar';
// import MainHeaderBar from '@/components/header/MainHeaderBar';

// const archivo = Archivo({
//   variable: '--font-archivo-sans',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div className='bg-base min-h-screen grid grid-cols-[310px_1fr] p-8 gap-7.5'>
//       <aside className=''>
//         <Sidebar />
//       </aside>

//       <div className='flex flex-col gap-7.5 min-h-0'>
//         <header>
//           <MainHeaderBar />
//         </header>
//         {/* <div>BreadCrumbs</div> */}
//         <main className='flex-1 bg-surface min-h-0'>{children}</main>
//       </div>
//     </div>
//   );
// }
